Squashed commit of the following:
commit b276c4fb7f9ef88c16e558e08f6e6120e2d276fb
Author: Qingnan Duan <duanqn_own_1@yeah.net>
Date:   Mon Aug 31 22:13:21 2020 +0800

    Fix parenthesis

commit 48b61c00c676dbb714b67015233514a3dcd5e614
Author: Qingnan Duan <duanqn_own_1@yeah.net>
Date:   Mon Aug 31 21:40:43 2020 +0800

    Fix MSVC warning C4805 and error C2416